name: Quests
author: naeng
main: naeng\quests\Quests
version: 1.5.6
api: 5.0.0
depend:
  - XuidCore
  - KorItemName
  - MailCore
  - SqlCore
softdepend:
  - Customies
  - DivingMine
  - FishPlugin
  - BossPlugin
  - VotifierAPI
  - NeighborPlugin
  - AttendanceCheck
  - RankPrefix
  - Warehouse
  - UserExchange
  - NeighborhoodShop
virions:
  - SOF3/await-generator/master
  - poggit/libasynql/4.0.0
  - presentkim-pm/nbt-serializer/3.0.0
  - presentkim-pm/item-serialize-utils/3.1.0
permissions:
  quests.staff.command:
    description: "퀘스트를 관리하기 위한 권한입니다"
    default: op
  quests.user.command:
    description: "퀘스트를 하기 위한 권한입니다"
    default: true