name: Quests
author: naeng
main: naeng\quests\Quests
version: 1.1.10
api: 5.0.0
depend:
  - XuidCore
  - NaengUtils
  - MailCore
virions:
  - SOF3/await-generator/master
  - jojoe77777/FormAPI/2.1.1
  - presentkim-pm/item-serialize-utils/3.1.0
permissions:
  quests.staff.command:
    description: "퀘스트를 관리하기 위한 권한입니다"
    default: op
  quests.user.command:
    description: "퀘스트를 하기 위한 권한입니다"
    default: true
