name: Quests
author: naeng
main: naeng\Quests\Quests
version: 1.0.6
api: 5.0.0
depend:
  - NaengUtils
  - MailCore
virions:
  - SOF3/await-generator/master
permissions:
  quests.staff.command:
    description: "퀘스트를 관리하기 위한 권한입니다"
    default: op
  quests.user.command:
    description: "퀘스트를 하기 위한 권한입니다"
    default: true
